name: webfetch
description: A Dart implementation of the Web Fetch API that allows you to make requests and process results just like using fetch in a browser.
version: 0.1.0
repository: https://github.com/medz/webfetch

environment:
  sdk: ^3.4.0

dependencies:
  mime: ^1.0.4
  web: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.21.0
